name: test
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8
  - ipykernel
  - numpy=1.20.0
  - youtube-dlp
  - librosa
  - pip:
    - openunmix
    - soundfile
    - basic-pitch
    - pretty_midi>= 0.2.8
    - bokeh= 2.4.0
    - visual_midi

# Additionally run conda install pytorch torchvision torchaudio pytorch-cuda=12.1 -c pytorch -c nvidia